// ACTION TYPES
export const GET_CAMPUSES = "GET_CAMPUSES";
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_CAMPUS = "GET_CAMPUS";
export const GET_STUDENT = "GET_STUDENT";
export const CREATE_CAMPUS = "CREATE_CAMPUS";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const DELETE_CAMPUS = "DELETE_CAMPUS";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const UPDATE_CAMPUS = "UPDATE_CAMPUS";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const UNREGISTER_STUDENT = "UNREGISTER_STUDENT";
export const REGISTER_STUDENT = "REGISTER_STUDENT";
